#ifndef _AIR_COMPARE_
#define _AIR_COMPARE_

#define AIR_BRAND_MIDEA			1
#define AIR_BRAND_MIDEA_LEN		63

#define AIR_BRAND_TOSHIBA		2
#define AIR_BRAND_TOSHIBA_LEN	58

#define AIR_BRAND_HAIER			3
#define AIR_BRAND_HAIER_LEN		123

#define AIR_BRAND_GREE 			4
#define AIR_BRAND_GREE_LEN		126

#define AIR_BRAND_CHIGO			5
#define AIR_BRAND_CHIGO_LEN		88

#define AIR_BRAND_OAKS			6
#define AIR_BRAND_OAKS_LEN		122

#define AIR_BRAND_CHUNLAN		7
#define AIR_BRAND_CHUNLAN_LEN	71

#define AIR_BRAND_LG 			8
#define AIR_BRAND_LG_LEN		65

#define AIR_BRAND_TCL			9
#define AIR_BRAND_TCL_LEN		68

#define AIR_BRAND_SAMSUNG		10
#define AIR_BRAND_SAMSUNG_LEN	124

#define AIR_BRAND_S_SAMSUNG		11
#define AIR_BRAND_S_SAMSUNG_ELN	30

#define AIR_BRAND_SANYO			12
#define AIR_BRAND_SANYO_LEN		129

#define AIR_BRAND_SHI 			13
#define AIR_BRAND_SHI_LEN 		157

#define AIR_BRAND_SE 			14
#define AIR_BRAND_SE_LEN		94

#define AIR_BRAND_CHANGHONG		15
#define AIR_BRAND_CHANGHONG_LEN	112

#define AIR_BRAND_PANASONIC		16
#define AIR_BRAND_PANASONIC_LEN	83

#define AIR_BRAND_SOM			17
#define AIR_BRAND_SOM_LEN		80

#define AIR_BRAND_UCHIDA		18
#define AIR_BRAND_UCHIDA_LEN	56

#define AIR_BRAND_HISENSE		19
#define AIR_BRAND_HISENSE_LEN	80

#define AIR_BRAND_SHINCO		20
#define AIR_BRAND_SHINCO_LEN	69

#define AIR_BRAND_HITACHI		21
#define AIR_BRAND_HITACHI_LEN	89

#define AIR_BRAND_HUALING		22
#define AIR_BRAND_HUALING_LEN	34

#define AIR_BRAND_KELON			23
#define AIR_BRAND_KELON_LEN		112

#define AIR_BRAND_WARBURG		24
#define AIR_BRAND_WARBURG_LEN	116

#define AIR_BRAND_MIGHT			25
#define AIR_BRAND_MIGHT_LEN		25

#define AIR_BRAND_CHANGLING		26
#define AIR_BRAND_CHANGLING_LEN	78

#define AIR_BRAND_YINGYAN		27
#define AIR_BRAND_YINGYAN_LEN	26

#define AIR_BRAND_BLUEWAVE		28
#define AIR_BRAND_BLUEWAVE_LEN	28

#define AIR_BRAND_RABBIT		29
#define AIR_BRAND_RABBIT_LEN	26

#define AIR_BRAND_CARRIER		30
#define AIR_BRAND_CARRIER_LEN	35

#define AIR_BRAND_TOHO			31
#define AIR_BRAND_TOHO_LEN		25

#define AIR_BRAND_GAOLUHUA		32
#define AIR_BRAND_GAOLUHUA_LEN	22

#define AIR_BRAND_AUCMA			33
#define AIR_BRAND_AUCMA_LEN		78

#define AIR_BRAND_SHENGFENG		34
#define AIR_BRAND_SHENGFENG_LEN	72

#define AIR_BRAND_YANGZI		35	
#define AIR_BRAND_YANGZI_LEN	23

#define AIR_BRAND_WHIRLPOOL		36
#define AIR_BRAND_WHIRLPOOL_LEN	22

#define AIR_BRAND_DAIKIN		37
#define AIR_BRAND_DAIKIN_LEN	116

#define AIR_BRAND_HSBC			38
#define AIR_BRAND_HSBC_LEN		21

#define AIR_BRAND_TOSHIBA2		39
#define AIR_BRAND_TOSHIBA2_LEN	97

#define AIR_BRAND_ELECTROLUX		40
#define AIR_BRAND_ELECTROLUX_LEN	98

#define AIR_BRAND_PANDA			41
#define AIR_BRAND_PANDA_LEN		29

#define AIR_BRAND_LINGON		42
#define AIR_BRAND_LINGON_LEN	21

#define AIR_BRAND_TIANYUAN		43
#define AIR_BRAND_TIANYUAN_LEN	21

#define AIR_BRAND_OTHER			44
#define AIR_BRAND_OTHER_LEN		831

#define AIR_BRAND_LILY			45
#define AIR_BRAND_LILY_LEN		291	

#define AIR_BRAND_SIMPLICRTY		46
#define AIR_BRAND_SIMPLICRTY_LEN	291

#define AIR_BRAND_DAEWOO		47
#define AIR_BRAND_DAEWOO_LEN	291

#define AIR_BRAND_CLARENT		48
#define AIR_BRAND_CLARENT_LEN	291

#define AIR_BRAND_COLONES		49
#define AIR_BRAND_COLONES_LEN	291

#define AIR_BRAND_SOUTHWIND		50
#define AIR_BRAND_SOUTHWIND_LEN	291

#define AIR_BRAND_KUNDA			51
#define AIR_BRAND_KUNDA_LEN		291

#define AIR_BRAND_YUSHCHENKO		52
#define AIR_BRAND_YUSHCHENKO_LEN	291

#define AIR_BRAND_FREENET		53
#define AIR_BRAND_FREENET_LEN	291

#define AIR_BRAND_SHENGFENG2		54
#define AIR_BRAND_SHENGFENG2_LEN	291

#define AIR_BRAND_THAILAND		55
#define AIR_BRAND_THAILAND_LEN	291

#define AIR_BRAND_GLANZ			56
#define AIR_BRAND_GLANZ_LEN		118

#define AIR_BRAND_LEROY			57
#define AIR_BRAND_LEROY_LEN		42

#define AIR_BRAND_FUJITSU		58
#define AIR_BRAND_FUJITSU_LEN	40

#define AIR_BRAND_YORK			59
#define AIR_BRAND_YORK_LEN		27

#define AIR_BRAND_MCQUAY		60
#define AIR_BRAND_MCQUAY_LEN	27

#define AIR_BRAND_SANKEN		61
#define AIR_BRAND_SANKEN_LEN	32

#define AIR_BRAND_POLYTRON		62
#define AIR_BRAND_POLYTRON_LEN	39

#define AIR_BRAND_SHARP			63
#define AIR_BRAND_SHARP_LEN		80

#define AIR_BRAND_ZHENBAO		64
#define AIR_BRAND_ZHENBAO_LEN	11

#define AIR_BRAND_WANBAO		65
#define AIR_BRAND_WANBAO_LEN	14

#define AIR_BRAND_YINGHUA		66
#define AIR_BRAND_YINGHUA_LEN	17

#define AIR_BRAND_AKUMA			67
#define AIR_BRAND_AKUMA_LEN		78

#define AIR_BRAND_AMCOR			68
#define AIR_BRAND_AMCOR_LEN		112

#define AIR_BRAND_POLYTONG		69
#define AIR_BRAND_POLYTONG_LEN	58

#define AIR_BRAND_NORTHSTART		70
#define AIR_BRAND_NORTHSTART_LEN	55

#define AIR_BRAND_POKAL			71
#define AIR_BRAND_POKAL_LEN		26

#define AIR_BRAND_BOSCH			72
#define AIR_BRAND_BOSCH_LEN		56

#define AIR_BRAND_BLUEWAY		73
#define AIR_BRAND_BLUEWAY_LEN	150

#define AIR_BRAND_CLIMASMART		74
#define AIR_BRAND_CLIMASMART_LEN	54

#define AIR_BRAND_BIGISLAND		75
#define AIR_BRAND_BIGISLAND_LEN	54

#define AIR_BRAND_DANBY			76
#define AIR_BRAND_DANBY_LEN		54

#define AIR_BRAND_NEWCONNAUGHT		77
#define AIR_BRAND_NEWCONNAUGHT_LEN	129

#define AIR_BRAND_DATONG		78
#define AIR_BRAND_DATONG_LEN	129

#define AIR_BRAND_DONGYUAN		79
#define AIR_BRAND_DONGYUAN_LEN	43

#define AIR_BRAND_JIPUSHENG		80
#define AIR_BRAND_JIPUSHENG_LEN	25

#define AIR_BRAND_DONGYUAN2		81
#define AIR_BRAND_DONGYUAN2_LEN	126

#define AIR_BRAND_TOYOTOMI		82
#define AIR_BRAND_TOYOTOMI_LEN	58

#define AIR_BRAND_GOLDSTART		83
#define AIR_BRAND_GOLDSTART_LEN	40

#define AIR_BRAND_ROSEAREFINE		84
#define AIR_BRAND_ROSEAREFINE_LEN	126

#define AIR_BRAND_HAMPTON		85
#define AIR_BRAND_HAMPTON_LEN	40

#define AIR_BRAND_FANTASIA		86
#define AIR_BRAND_FANTASIA_LEN	40

#define AIR_BRAND_JICAIRUI		87
#define AIR_BRAND_JICAIRUI_LEN	40

#define AIR_BRAND_JINBEIJING		88
#define AIR_BRAND_JINBEIJING_LEN	8

#define AIR_BRAND_KANGBAIEN		89
#define AIR_BRAND_KANGBAIEN_LEN	112

#define AIR_BRAND_CORONA		90
#define AIR_BRAND_CORONA_LEN	56

#define AIR_BRAND_NEWLATTICE		91
#define AIR_BRAND_NEWLATTICE_LEN	40

#define AIR_BRAND_KIOWA			92
#define AIR_BRAND_KIOWA_LEN		73

#define AIR_BRAND_KOMECO		93
#define AIR_BRAND_KOMECO_LEN	73

#define AIR_BRAND_LANSTART		94
#define AIR_BRAND_LANSTART_LEN	72

#define AIR_BRAND_CROSS			95
#define AIR_BRAND_CROSS_LEN		66

#define AIR_BRAND_LELETTER		96
#define AIR_BRAND_LELETTER_LEN	83

#define AIR_BRAND_HUAMEI		97
#define AIR_BRAND_HUAMEI_LEN	14

#define AIR_BRAND_MDV			98
#define AIR_BRAND_MDV_LEN		73

#define AIR_BRAND_BELCANTO		99
#define AIR_BRAND_BELCANTO_LEN	123

#define AIR_BRAND_MILLER		100
#define AIR_BRAND_MILLER_LEN	73

#define AIR_BRAND_NATIONAL		101
#define AIR_BRAND_NATIONAL_LEN	126

#define AIR_BRAND_OAK 			102
#define AIR_BRAND_OAK_LEN 		122

#define AIR_BRAND_OUZHENBAO		103
#define AIR_BRAND_OUZHENBAO_LEN	40

#define AIR_BRAND_PREMIER		104
#define AIR_BRAND_PREMIER_LEN	73

#define AIR_BRAND_QINGYUAN		105
#define AIR_BRAND_QINGYUAN_LEN	73

#define AIR_BRAND_THENEW		106
#define AIR_BRAND_THENEW_LEN	70

#define AIR_BRAND_LINGBAO		107
#define AIR_BRAND_LINGBAO_LEN	73

#define AIR_BRAND_TWOLING		108
#define AIR_BRAND_TWOLING_LEN	94

#define AIR_BRAND_LING 			109
#define AIR_BRAND_LING_LEN 		91

#define AIR_BRAND_XLING			110
#define AIR_BRAND_XLING_LEN		91

#define AIR_BRAND_THREEDRILL		111
#define AIR_BRAND_THREEDRILL_LEN	112

#define AIR_BRAND_SEARS				112
#define AIR_BRAND_SEARS_LEN			40

#define AIR_BRAND_SAMPO				113
#define AIR_BRAND_SAMPO_LEN			40

#define AIR_BRAND_SHUANGLU			114
#define AIR_BRAND_SHUANGLU_LEN		157

#define AIR_BRAND_SOYEA				115
#define AIR_BRAND_SOYEA_LEN			157

#define AIR_BRAND_EYRE 				116
#define AIR_BRAND_EYRE_LEN			40

#define AIR_BRAND_SONIA				117
#define AIR_BRAND_SONIA_LEN			73

#define AIR_BRAND_TADIRAN			118
#define AIR_BRAND_TADIRAN_LEN		73

#define AIR_BRAND_XTIANYUAN			119
#define AIR_BRAND_XTIANYUAN_LEN		28

#define AIR_BRAND_GENERAL			120
#define AIR_BRAND_GENERAL_LEN		40

#define AIR_BRAND_UNIAIR			121
#define AIR_BRAND_UNIAIR_LEN		73

#define AIR_BRAND_MACRO				122
#define AIR_BRAND_MACRO_LEN			112

#define AIR_BRAND_WEIYOUKANG		123
#define AIR_BRAND_WEIYOUKANG_LEN	73

#define AIR_BRAND_LGWHISEN			124
#define AIR_BRAND_LGWHISEN_LEN		65

#define AIR_BRAND_WANSHIYI			125
#define AIR_BRAND_WANSHIYI_LEN		26

#define AIR_BRAND_LITTLESWAN		126
#define AIR_BRAND_LITTLESWAN_LEN	73

#define AIR_BRAND_XIERMODEL			127
#define AIR_BRAND_XIERMODEL_LEN		40

#define AIR_BRAND_SNOW				128
#define AIR_BRAND_SNOW_LEN			140

#define AIR_BRAND_YAMATSU			129
#define AIR_BRAND_YAMATSU_LEN		118

#define AIR_BRAND_SUNSHINE			130
#define AIR_BRAND_SUNSHINE_LEN		73

#define AIR_BRAND_ELECTRA			131
#define AIR_BRAND_ELECTRA_LEN		68

#define AIR_BRAND_YONGAN			132
#define AIR_BRAND_YONGAN_LEN		91

#define AIR_BRAND_MOON_RABBIT		133
#define AIR_BRAND_MOON_RABBIT_LEN	91

#define AIR_BRAND_ZAMIR				134
#define AIR_BRAND_ZAMIR_LEN			73

#define AIR_BRAND_LONGFU			135
#define AIR_BRAND_LONGFU_LEN		831

#define AIR_BRAND_DUCKLING			136
#define AIR_BRAND_DUCKLING_LEN		831

#define AIR_BRAND_WINIA				137
#define AIR_BRAND_WINIA_LEN			831

#define AIR_BRAND_TRANE 			138
#define AIR_BRAND_TRANE_LEN			831

#define AIR_BRAND_CHINA 			139
#define AIR_BRAND_CHINA_LEN			831

#define AIR_BRAND_KONKA				140
#define AIR_BRAND_KONKA_LEN			831

#define AIR_BRAND_HELIAN			141
#define AIR_BRAND_HELIAN_LEN		831

#define AIR_BRAND_SONGLIN			142
#define AIR_BRAND_SONGLIN_LEN		831

#define AIR_BRAND_DEERFLY			143
#define AIR_BRAND_DEERFLY_LEN		831

#define AIR_BRAND_FLYCO				144
#define AIR_BRAND_FLYCO_LEN			831

#define AIR_BRAND_SAKADONGWOODA		145
#define AIR_BRAND_SAKADONGWOODA_LEN	831

#define AIR_BRAND_KOBE				146
#define AIR_BRAND_KOBE_LEN			831

#define AIR_BRAND_DATONGCOMPANY		147
#define AIR_BRAND_DATONGCOMPANY_LEN	48

#define AIR_BRAND_TEAC				148
#define AIR_BRAND_TEAC_LEN			42

#define AIR_BRAND_TOYO 				149
#define AIR_BRAND_TOYO_LEN 			46

#define AIR_BRAND_SONG 				150
#define AIR_BRAND_SONG_LEN 			48

#define AIR_BRAND_FORTRESS			151
#define AIR_BRAND_FORTRESS_LEN		48

#define AIR_BRAND_FUNAI				152
#define AIR_BRAND_FUNAI_LEN			42

#define AIR_BRAND_GE 				153
#define AIR_BRAND_GE_LEN 			46

#define AIR_BRAND_GWELL				154
#define AIR_BRAND_GWELL_LEN			40

#define AIR_BRAND_TAB 				155
#define AIR_BRAND_TAB_LEN 			42

#define AIR_BRAND_HERMAN			156
#define AIR_BRAND_HERMAN_LEN		39

#define AIR_BRAND_ANCROWN			157
#define AIR_BRAND_ANCROWN_LEN		48

#define AIR_BRAND_XWANSHIYI 		158
#define AIR_BRAND_XWANSHIYI_LEN		48

#define AIR_BRAND_MODERN			159
#define AIR_BRAND_MODERN_LEN		37

#define AIR_BRAND_XINLE 			160
#define AIR_BRAND_XINLE_LEN			40

#define AIR_BRAND_WESTINGHOUSE		161
#define AIR_BRAND_WESTINGHOUSE_LEN	48

#define AIR_BRAND_YUDIAN			162
#define AIR_BRAND_YUDIAN_LEN		50

#define AIR_BRAND_SWAN 				163
#define AIR_BRAND_SWAN_LEN 			42

#define AIR_BRAND_SACON				164
#define AIR_BRAND_SACON_LEN			46

#define AIR_BRAND_STILLJONAS		165
#define AIR_BRAND_STILLJONAS_LEN	38

#define AIR_BRAND_RASONIC			166
#define AIR_BRAND_RASONIC_LEN		42

#define AIR_BRAND_NIKKO				167
#define AIR_BRAND_NIKKO_LEN			39

#define AIR_BRAND_PROTON			168
#define AIR_BRAND_PROTON_LEN		48

#define AIR_BRAND_HUAWEI			169
#define AIR_BRAND_HUAWEI_LEN		54

#define AIR_BRAND_WELLCOME			170
#define AIR_BRAND_WELLCOME_LEN		43

#define AIR_BRAND_LENNOX			171
#define AIR_BRAND_LENNOX_LEN		46

#define AIR_BRAND_LIANGFENG			172
#define AIR_BRAND_LIANGFENG_LEN		38

#define AIR_BRAND_LIKEL				173
#define AIR_BRAND_LIKEL_LEN			40

#define AIR_BRAND_APTON 			174
#define AIR_BRAND_APTON_LEN 		126

#define AIR_BRAND_ALL 				175
#define AIR_BRAND_ALL_LEN			831

unsigned short getAirCompareResult(unsigned char *data,unsigned short brand);
unsigned char stringToHex(unsigned char *data);

//由品牌及产品id得到数据库中对应的id
unsigned int getAirIdInDb(unsigned short brand, unsigned short id);

void testExchange(void);

#endif