#include "AirInfo.h"
#include "AirCompare.h"
#include <stdio.h>

unsigned short getAirBrandNameById(unsigned short id, unsigned char language, char *name)
{
	if (language)
	{
		switch (id)
		{
		case AIR_BRAND_MIDEA:
			strcpy(name, "美的");
			return strlen("美的");
		case AIR_BRAND_TOSHIBA:
			strcpy(name, "东芝");
			return strlen("东芝");
		case AIR_BRAND_HAIER:
			strcpy(name, "海尔");
			return strlen("海尔");
		case AIR_BRAND_GREE:
			strcpy(name, "格力");
			return strlen("格力");
		case AIR_BRAND_CHIGO:
			strcpy(name, "志高");
			return strlen("志高");
		case AIR_BRAND_OAKS:
			strcpy(name,"奥克斯");
			return strlen("奥克斯");
		case AIR_BRAND_CHUNLAN:
			strcpy(name,"春兰");
			return strlen("春兰");
		case AIR_BRAND_LG:
			strcpy(name,"LG");
			return strlen("LG");
		case AIR_BRAND_TCL:
			strcpy(name,"TCL");
			return strlen("TCL");
		case AIR_BRAND_SAMSUNG:
			strcpy(name,"三星");
			return strlen("三星");
		case AIR_BRAND_S_SAMSUNG:
			strcpy(name,"小三星");
			return strlen("小三星");
		case AIR_BRAND_SANYO:
			strcpy(name,"三洋");
			return strlen("三洋");
		case AIR_BRAND_SHI:
			strcpy(name,"三凌重工");
			return strlen("三凌重工");
		case AIR_BRAND_SE:
			strcpy(name,"三凌机电");
			return strlen("三凌机电");
		case AIR_BRAND_CHANGHONG:
			strcpy(name,"长虹");
			return strlen("长虹");
		case AIR_BRAND_PANASONIC:
			strcpy(name,"松下");
			return strlen("松下");
		case AIR_BRAND_SOM:
			strcpy(name,"乐声");
			return strlen("乐声");
		case AIR_BRAND_UCHIDA:
			strcpy(name,"内田");
			return strlen("内田");
		case AIR_BRAND_HISENSE:
			strcpy(name,"海信");
			return strlen("海信");
		case AIR_BRAND_SHINCO:
			strcpy(name,"新科");
			return strlen("新科");
		case AIR_BRAND_HITACHI:
			strcpy(name,"日立");
			return strlen("日立");
		case AIR_BRAND_HUALING:
			strcpy(name,"华凌");
			return strlen("华凌");
		case AIR_BRAND_KELON:
			strcpy(name,"科龙");
			return strlen("科龙");
		case AIR_BRAND_WARBURG:
			strcpy(name,"华宝");
			return strlen("华宝");
		case AIR_BRAND_MIGHT:
			strcpy(name,"威力");
			return strlen("威力");
		case AIR_BRAND_CHANGLING:
			strcpy(name,"长岭");
			return strlen("长岭");
		case AIR_BRAND_YINGYAN:
			strcpy(name,"迎燕");
			return strlen("迎燕");
		case AIR_BRAND_BLUEWAVE:
			strcpy(name,"蓝波");
			return strlen("蓝波");
		case AIR_BRAND_RABBIT:
			strcpy(name,"玉兔");
			return strlen("玉兔");
		case AIR_BRAND_CARRIER:
			strcpy(name,"开利");
			return strlen("开利");
		case AIR_BRAND_TOHO:
			strcpy(name, "东宝");
			return strlen("东宝");
		case AIR_BRAND_GAOLUHUA:
			strcpy(name, "高路华");
			return strlen("高路华");
		case AIR_BRAND_AUCMA:
			strcpy(name, "澳柯玛");
			return strlen("澳柯玛");
		case AIR_BRAND_SHENGFENG:
			strcpy(name, "胜风1");
			return strlen("胜风1");
		case AIR_BRAND_YANGZI:
			strcpy(name, "扬子");
			return strlen("扬子");
		case AIR_BRAND_WHIRLPOOL:
			strcpy(name, "惠而浦");
			return strlen("惠而浦");
		case AIR_BRAND_DAIKIN:
			strcpy(name, "大金");
			return strlen("大金");
		case AIR_BRAND_HSBC:
			strcpy(name, "汇丰");
			return strlen("汇丰");
		case AIR_BRAND_TOSHIBA2:
			strcpy(name, "东芝2");
			return strlen("东芝2");
		case AIR_BRAND_ELECTROLUX:
			strcpy(name, "伊莱克斯");
			return strlen("伊莱克斯");
		case AIR_BRAND_PANDA:
			strcpy(name, "熊猫");
			return strlen("熊猫");
		case AIR_BRAND_LINGON:
			strcpy(name, "上凌");
			return strlen("上凌");
		case AIR_BRAND_TIANYUAN:
			strcpy(name, "天元");
			return strlen("天元");
		case AIR_BRAND_OTHER:
			strcpy(name, "其它品牌");
			return strlen("其它品牌");
		case AIR_BRAND_LILY:
			strcpy(name, "百合");
			return strlen("百合");
		case AIR_BRAND_SIMPLICRTY:
			strcpy(name, "SimpLlcrty");
			return strlen("SimpLlcrty");
		case AIR_BRAND_DAEWOO:
			strcpy(name, "大宇");
			return strlen("大宇");
		case AIR_BRAND_CLARENT:
			strcpy(name, "冠远");
			return strlen("冠远");
		case AIR_BRAND_COLONES:
			strcpy(name, "科朗");
			return strlen("科朗");
		case AIR_BRAND_SOUTHWIND:
			strcpy(name, "南风");
			return strlen("南风");
		case AIR_BRAND_KUNDA:
			strcpy(name, "群达");
			return strlen("群达");
		case AIR_BRAND_YUSHCHENKO:
			strcpy(name, "先科");
			return strlen("先科");
		case AIR_BRAND_FREENET:
			strcpy(name, "新飞");
			return strlen("新飞");
		case AIR_BRAND_SHENGFENG2:
			strcpy(name, "胜风2");
			return strlen("胜风2");
		case AIR_BRAND_THAILAND:
			strcpy(name, "泰国");
			return strlen("泰国");
		case AIR_BRAND_GLANZ:
			strcpy(name, "格兰仕");
			return strlen("格兰仕");
		case AIR_BRAND_LEROY:
			strcpy(name, "乐华");
			return strlen("乐华");
		case AIR_BRAND_FUJITSU:
			strcpy(name, "富士通");
			return strlen("富士通");
		case AIR_BRAND_YORK:
			strcpy(name, "约克");
			return strlen("约克");
		case AIR_BRAND_MCQUAY:
			strcpy(name, "麦克维尔");
			return strlen("麦克维尔");
		case AIR_BRAND_SANKEN:
			strcpy(name, "三垦");
			return strlen("三垦");
		case AIR_BRAND_POLYTRON:
			strcpy(name, "宝立创");
			return strlen("宝立创");
		case AIR_BRAND_SHARP:
			strcpy(name, "夏普");
			return strlen("夏普");
		case AIR_BRAND_ZHENBAO:
			strcpy(name, "镇堡");
			return strlen("镇堡");
		case AIR_BRAND_WANBAO:
			strcpy(name, "万宝");
			return strlen("万宝");
		case AIR_BRAND_YINGHUA:
			strcpy(name, "樱花");
			return strlen("樱花");
		case AIR_BRAND_AKUMA:
			strcpy(name, "Akuma");
			return strlen("Akuma");
		case AIR_BRAND_AMCOR:
			strcpy(name, "Amcor");
			return strlen("Amcor");
		case AIR_BRAND_POLYTONG:
			strcpy(name, "保利通");
			return strlen("保利通");
		case AIR_BRAND_NORTHSTART:
			strcpy(name, "北极星");
			return strlen("北极星");
		case AIR_BRAND_POKAL:
			strcpy(name, "波卡尔");
			return strlen("波卡尔");
		case AIR_BRAND_BOSCH:
			strcpy(name, "博世");
			return strlen("博世");
		case AIR_BRAND_BLUEWAY:
			strcpy(name, "蓝光");
			return strlen("蓝光");
		case AIR_BRAND_CLIMASMART:
			strcpy(name, "ClimaSmart");
			return strlen("ClimaSmart");
		case AIR_BRAND_BIGISLAND:
			strcpy(name, "大岛");
			return strlen("大岛");
		case AIR_BRAND_DANBY:
			strcpy(name, "丹比");
			return strlen("丹比");
		case AIR_BRAND_NEWCONNAUGHT:
			strcpy(name, "新诺");
			return strlen("新诺");
		case AIR_BRAND_DATONG:
			strcpy(name, "大同");
			return strlen("大同");
		case AIR_BRAND_DONGYUAN:
			strcpy(name, "东元");
			return strlen("东元");
		case AIR_BRAND_JIPUSHENG:
			strcpy(name, "吉普生");
			return strlen("吉普生");
		case AIR_BRAND_DONGYUAN2:
			strcpy(name, "东元2");
			return strlen("东元2");
		case AIR_BRAND_TOYOTOMI:
			strcpy(name, "丰臣");
			return strlen("丰臣");
		case AIR_BRAND_GOLDSTART:
			strcpy(name, "高士达");
			return strlen("高士达");
		case AIR_BRAND_ROSEAREFINE:
			strcpy(name, "瑰都细斯");
			return strlen("瑰都细斯");
		case AIR_BRAND_HAMPTON:
			strcpy(name, "汉普顿");
			return strlen("汉普顿");
		case AIR_BRAND_FANTASIA:
			strcpy(name, "幻想曲");
			return strlen("幻想曲");
		case AIR_BRAND_JICAIRUI:
			strcpy(name, "吉菜瑞");
			return strlen("吉菜瑞");
		case AIR_BRAND_JINBEIJING:
			strcpy(name, "金北京");
			return strlen("金北京");
		case AIR_BRAND_KANGBAIEN:
			strcpy(name, "康拜恩");
			return strlen("康拜恩");
		case AIR_BRAND_CORONA:
			strcpy(name, "可乐娜");
			return strlen("可乐娜");
		case AIR_BRAND_NEWLATTICE:
			strcpy(name, "新格");
			return strlen("新格");
		case AIR_BRAND_KIOWA:
			strcpy(name, "基奥瓦");
			return strlen("基奥瓦");
		case AIR_BRAND_KOMECO:
			strcpy(name, "广镁");
			return strlen("广镁");
		case AIR_BRAND_LANSTART:
			strcpy(name, "蓝星");
			return strlen("蓝星");
		case AIR_BRAND_CROSS:
			strcpy(name, "乐士");
			return strlen("乐士");
		case AIR_BRAND_LELETTER:
			strcpy(name, "乐信");
			return strlen("乐信");
		case AIR_BRAND_HUAMEI:
			strcpy(name, "华美");
			return strlen("华美");
		case AIR_BRAND_MDV:
			strcpy(name, "MDV");
			return strlen("MDV");
		case AIR_BRAND_BELCANTO:
			strcpy(name, "美歌");
			return strlen("美歌");
		case AIR_BRAND_MILLER:
			strcpy(name, "米勒");
			return strlen("米勒");
		case AIR_BRAND_NATIONAL:
			strcpy(name, "松下早期");
			return strlen("松下早期");
		case AIR_BRAND_OAK:
			strcpy(name, "欧锴");
			return strlen("欧锴");
		case AIR_BRAND_OUZHENBAO:
			strcpy(name, "欧珍宝");
			return strlen("欧珍宝");
		case AIR_BRAND_PREMIER:
			strcpy(name, "拍得丽");
			return strlen("拍得丽");
		case AIR_BRAND_QINGYUAN:
			strcpy(name, "庆元");
			return strlen("庆元");
		case AIR_BRAND_THENEW:
			strcpy(name, "日新");
			return strlen("日新");
		case AIR_BRAND_LINGBAO:
			strcpy(name, "凌宝");
			return strlen("凌宝");
		case AIR_BRAND_TWOLING:
			strcpy(name, "二凌");
			return strlen("二凌");
		case AIR_BRAND_LING:
			strcpy(name, "三凌");
			return strlen("三凌");
		case AIR_BRAND_XLING:
			strcpy(name, "三菱");
			return strlen("三菱");
		case AIR_BRAND_THREEDRILL:
			strcpy(name, "三钻");
			return strlen("三钻");
		case AIR_BRAND_SEARS:
			strcpy(name, "西尔斯");
			return strlen("西尔斯");
		case AIR_BRAND_SAMPO:
			strcpy(name, "声宝");
			return strlen("声宝");
		case AIR_BRAND_SHUANGLU:
			strcpy(name, "双鹿");
			return strlen("双鹿");
		case AIR_BRAND_SOYEA:
			strcpy(name, "数源");
			return strlen("数源");
		case AIR_BRAND_EYRE:
			strcpy(name, "舒适艾尔");
			return strlen("舒适艾尔");
		case AIR_BRAND_SONIA:
			strcpy(name, "索尼埃");
			return strlen("索尼埃");
		case AIR_BRAND_TADIRAN:
			strcpy(name, "塔迪兰");
			return strlen("塔迪兰");
		case AIR_BRAND_XTIANYUAN:
			strcpy(name, "田源");
			return strlen("田源");
		case AIR_BRAND_GENERAL:
			strcpy(name, "通用");
			return strlen("通用");
		case AIR_BRAND_UNIAIR:
			strcpy(name, "立荣");
			return strlen("立荣");
		case AIR_BRAND_MACRO:
			strcpy(name, "万家乐");
			return strlen("万家乐");
		case AIR_BRAND_WEIYOUKANG:
			strcpy(name, "维友康");
			return strlen("维友康");
		case AIR_BRAND_LGWHISEN:
			strcpy(name, "LG Whisen");
			return strlen("LG Whisen");
		case AIR_BRAND_WANSHIYI:
			strcpy(name, "万事益");
			return strlen("万事益");
		case AIR_BRAND_LITTLESWAN:
			strcpy(name, "小天鹅");
			return strlen("小天鹅");
		case AIR_BRAND_XIERMODEL:
			strcpy(name, "熙尔楷模");
			return strlen("熙尔楷模");
		case AIR_BRAND_SNOW:
			strcpy(name, "雪花");
			return strlen("雪花");
		case AIR_BRAND_YAMATSU:
			strcpy(name, "亚马逊");
			return strlen("亚马逊");
		case AIR_BRAND_SUNSHINE:
			strcpy(name, "阳光");
			return strlen("阳光");
		case AIR_BRAND_ELECTRA:
			strcpy(name, "以莱特");
			return strlen("以莱特");
		case AIR_BRAND_YONGAN:
			strcpy(name, "永安");
			return strlen("永安");
		case AIR_BRAND_MOON_RABBIT:
			strcpy(name, "月兔");
			return strlen("月兔");
		case AIR_BRAND_ZAMIR:
			strcpy(name, "扎米尔");
			return strlen("扎米尔");
		case AIR_BRAND_LONGFU:
			strcpy(name, "长府");
			return strlen("长府");
		case AIR_BRAND_DUCKLING:
			strcpy(name, "小鸭");
			return strlen("小鸭");
		case AIR_BRAND_WINIA:
			strcpy(name, "云雅");
			return strlen("云雅");
		case AIR_BRAND_TRANE:
			strcpy(name, "特灵");
			return strlen("特灵");
		case AIR_BRAND_CHINA:
			strcpy(name, "首华");
			return strlen("首华");
		case AIR_BRAND_KONKA:
			strcpy(name, "康佳");
			return strlen("康佳");
		case AIR_BRAND_HELIAN:
			strcpy(name, "禾联");
			return strlen("禾联");
		case AIR_BRAND_SONGLIN:
			strcpy(name, "歌林");
			return strlen("歌林");
		case AIR_BRAND_DEERFLY:
			strcpy(name, "飞鹿");
			return strlen("飞鹿");
		case AIR_BRAND_FLYCO:
			strcpy(name, "飞科");
			return strlen("飞科");
		case AIR_BRAND_SAKADONGWOODA:
			strcpy(name, "东佑达");
			return strlen("东佑达");
		case AIR_BRAND_KOBE:
			strcpy(name, "阪神");
			return strlen("阪神");
		case AIR_BRAND_DATONGCOMPANY:
			strcpy(name, "大同公司");
			return strlen("大同公司");
		case AIR_BRAND_TEAC:
			strcpy(name, "蒂雅克");
			return strlen("蒂雅克");
		case AIR_BRAND_TOYO:
			strcpy(name, "东洋");
			return strlen("东洋");
		case AIR_BRAND_SONG:
			strcpy(name, "飞歌");
			return strlen("飞歌");
		case AIR_BRAND_FORTRESS:
			strcpy(name, "丰泽");
			return strlen("丰泽");
		case AIR_BRAND_FUNAI:
			strcpy(name, "福奈");
			return strlen("福奈");
		case AIR_BRAND_GE:
			strcpy(name, "通用电器");
			return strlen("通用电器");
		case AIR_BRAND_GWELL:
			strcpy(name, "格威尔");
			return strlen("格威尔");
		case AIR_BRAND_TAB:
			strcpy(name, "古桥");
			return strlen("古桥");
		case AIR_BRAND_HERMAN:
			strcpy(name, "贺曼");
			return strlen("贺曼");
		case AIR_BRAND_ANCROWN:
			strcpy(name, "皇冠");
			return strlen("皇冠");
		case AIR_BRAND_XWANSHIYI:
			strcpy(name, "X万士益");
			return strlen("X万士益");
		case AIR_BRAND_MODERN:
			strcpy(name, "现代");
			return strlen("现代");
		case AIR_BRAND_XINLE:
			strcpy(name, "新乐");
			return strlen("新乐");
		case AIR_BRAND_WESTINGHOUSE:
			strcpy(name, "西屋");
			return strlen("西屋");
		case AIR_BRAND_YUDIAN:
			strcpy(name, "宇电");
			return strlen("宇电");
		case AIR_BRAND_SWAN:
			strcpy(name, "天鹅");
			return strlen("天鹅");
		case AIR_BRAND_SACON:
			strcpy(name, "帅康");
			return strlen("帅康");
		case AIR_BRAND_STILLJONAS:
			strcpy(name, "尚纳斯");
			return strlen("尚纳斯");
		case AIR_BRAND_RASONIC:
			strcpy(name, "信兴乐信");
			return strlen("信兴乐信");
		case AIR_BRAND_NIKKO:
			strcpy(name, "日高");
			return strlen("日高");
		case AIR_BRAND_PROTON:
			strcpy(name, "普腾");
			return strlen("普腾");
		case AIR_BRAND_HUAWEI:
			strcpy(name, "华为");
			return strlen("华为");
		case AIR_BRAND_WELLCOME:
			strcpy(name, "惠康");
			return strlen("惠康");
		case AIR_BRAND_LENNOX:
			strcpy(name, "雷诺士");
			return strlen("雷诺士");
		case AIR_BRAND_LIANGFENG:
			strcpy(name, "良峰");
			return strlen("良峰");
		case AIR_BRAND_LIKEL:
			strcpy(name, "利凯尔");
			return strlen("利凯尔");
		case AIR_BRAND_APTON:
			strcpy(name, "艾普顿");
			return strlen("艾普顿");
		case AIR_BRAND_ALL:
			strcpy(name, "全部");
			return strlen("全部");
		}
	}
	
}

unsigned short getAirBrandProductLenById(unsigned short id)
{
	switch (id)
	{
	case AIR_BRAND_MIDEA:
		return AIR_BRAND_MIDEA_LEN;
	case AIR_BRAND_TOSHIBA:
		return AIR_BRAND_MIDEA_LEN;
	case AIR_BRAND_HAIER:
		return AIR_BRAND_HAIER_LEN;
	case AIR_BRAND_GREE:
		return AIR_BRAND_GREE_LEN;
	case AIR_BRAND_CHIGO:
		return AIR_BRAND_CHIGO_LEN;
	case AIR_BRAND_OAKS:
		return AIR_BRAND_OAKS_LEN;
	case AIR_BRAND_CHUNLAN:
		return AIR_BRAND_CHUNLAN_LEN;
	case AIR_BRAND_LG:
		return AIR_BRAND_LG_LEN;
	case AIR_BRAND_TCL:
		return AIR_BRAND_TCL_LEN;
	case AIR_BRAND_SAMSUNG:
		return AIR_BRAND_SAMSUNG_LEN;
	case AIR_BRAND_S_SAMSUNG:
		return AIR_BRAND_S_SAMSUNG_ELN;
	case AIR_BRAND_SANYO:
		return AIR_BRAND_SANYO_LEN;
	case AIR_BRAND_SHI:
		return AIR_BRAND_SHI_LEN;
	case AIR_BRAND_SE:
		return AIR_BRAND_SE_LEN;
	case AIR_BRAND_CHANGHONG:
		return AIR_BRAND_CHANGHONG_LEN;
	case AIR_BRAND_PANASONIC:
		return AIR_BRAND_PANASONIC_LEN;
	case AIR_BRAND_SOM:
		return AIR_BRAND_SOM_LEN;
	case AIR_BRAND_UCHIDA:
		return AIR_BRAND_UCHIDA_LEN;
	case AIR_BRAND_HISENSE:
		return AIR_BRAND_HISENSE_LEN;
	case AIR_BRAND_SHINCO:
		return AIR_BRAND_SHINCO_LEN;
	case AIR_BRAND_HITACHI:
		return AIR_BRAND_HITACHI_LEN;
	case AIR_BRAND_HUALING:
		return AIR_BRAND_HUALING_LEN;
	case AIR_BRAND_KELON:
		return AIR_BRAND_KELON_LEN;
	case AIR_BRAND_WARBURG:
		return AIR_BRAND_WARBURG_LEN;
	case AIR_BRAND_MIGHT:
		return AIR_BRAND_MIGHT_LEN;
	case AIR_BRAND_CHANGLING:
		return AIR_BRAND_CHANGLING_LEN;
	case AIR_BRAND_YINGYAN:
		return AIR_BRAND_YINGYAN_LEN;
	case AIR_BRAND_BLUEWAVE:
		return AIR_BRAND_BLUEWAVE_LEN;
	case AIR_BRAND_RABBIT:
		return AIR_BRAND_RABBIT_LEN;
	case AIR_BRAND_CARRIER:
		return AIR_BRAND_CARRIER_LEN;
	case AIR_BRAND_TOHO:
		return AIR_BRAND_TOHO_LEN;
	case AIR_BRAND_GAOLUHUA:
		return AIR_BRAND_GAOLUHUA_LEN;
	case AIR_BRAND_AUCMA:
		return AIR_BRAND_AUCMA_LEN;
	case AIR_BRAND_SHENGFENG:
		return AIR_BRAND_SHENGFENG_LEN;
	case AIR_BRAND_YANGZI:
		return AIR_BRAND_YANGZI_LEN;
	case AIR_BRAND_WHIRLPOOL:
		return AIR_BRAND_WHIRLPOOL_LEN;
	case AIR_BRAND_DAIKIN:
		return AIR_BRAND_DAIKIN_LEN;
	case AIR_BRAND_HSBC:
		return AIR_BRAND_HSBC_LEN;
	case AIR_BRAND_TOSHIBA2:
		return AIR_BRAND_TOSHIBA2_LEN;
	case AIR_BRAND_ELECTROLUX:
		return AIR_BRAND_ELECTROLUX_LEN;
	case AIR_BRAND_PANDA:
		return AIR_BRAND_PANDA_LEN;
	case AIR_BRAND_LINGON:
		return AIR_BRAND_LINGON_LEN;
	case AIR_BRAND_TIANYUAN:
		return AIR_BRAND_TIANYUAN;
	case AIR_BRAND_OTHER:
		return AIR_BRAND_OTHER;
	case AIR_BRAND_LILY:
		return AIR_BRAND_LILY_LEN;
	case AIR_BRAND_SIMPLICRTY:
		return AIR_BRAND_SIMPLICRTY_LEN;
	case AIR_BRAND_DAEWOO:
		return AIR_BRAND_DAEWOO_LEN;
	case AIR_BRAND_CLARENT:
		return AIR_BRAND_CLARENT_LEN;
	case AIR_BRAND_COLONES:
		return AIR_BRAND_COLONES_LEN;
	case AIR_BRAND_SOUTHWIND:
		return AIR_BRAND_SOUTHWIND_LEN;
	case AIR_BRAND_KUNDA:
		return AIR_BRAND_KUNDA_LEN;
	case AIR_BRAND_YUSHCHENKO:
		return AIR_BRAND_YUSHCHENKO_LEN;
	case AIR_BRAND_FREENET:
		return AIR_BRAND_FREENET_LEN;
	case AIR_BRAND_SHENGFENG2:
		return AIR_BRAND_SHENGFENG2_LEN;
	case AIR_BRAND_THAILAND:
		return AIR_BRAND_THAILAND_LEN;
	case AIR_BRAND_GLANZ:
		return AIR_BRAND_GLANZ_LEN;
	case AIR_BRAND_LEROY:
		return AIR_BRAND_LEROY_LEN;
	case AIR_BRAND_FUJITSU:
		return AIR_BRAND_FUJITSU_LEN;
	case AIR_BRAND_YORK:
		return AIR_BRAND_YORK_LEN;
	case AIR_BRAND_MCQUAY:
		return AIR_BRAND_MCQUAY_LEN;
	case AIR_BRAND_SANKEN:
		return AIR_BRAND_SANKEN_LEN;
	case AIR_BRAND_POLYTRON:
		return AIR_BRAND_POLYTRON_LEN;
	case AIR_BRAND_SHARP:
		return AIR_BRAND_SHARP_LEN;
	case AIR_BRAND_ZHENBAO:
		return AIR_BRAND_ZHENBAO_LEN;
	case AIR_BRAND_WANBAO:
		return AIR_BRAND_WANBAO_LEN;
	case AIR_BRAND_YINGHUA:
		return AIR_BRAND_YINGHUA_LEN;
	case AIR_BRAND_AKUMA:
		return AIR_BRAND_AKUMA_LEN;
	case AIR_BRAND_AMCOR:
		return AIR_BRAND_AMCOR_LEN;
	case AIR_BRAND_POLYTONG:
		return AIR_BRAND_POLYTONG_LEN;
	case AIR_BRAND_NORTHSTART:
		return AIR_BRAND_NORTHSTART_LEN;
	case AIR_BRAND_POKAL:
		return AIR_BRAND_POKAL_LEN;
	case AIR_BRAND_BOSCH:
		return AIR_BRAND_BOSCH_LEN;
	case AIR_BRAND_BLUEWAY:
		return AIR_BRAND_BLUEWAY_LEN;
	case AIR_BRAND_CLIMASMART:
		return AIR_BRAND_CLIMASMART_LEN;
	case AIR_BRAND_BIGISLAND:
		return AIR_BRAND_BIGISLAND_LEN;
	case AIR_BRAND_DANBY:
		return AIR_BRAND_DANBY_LEN;
	case AIR_BRAND_NEWCONNAUGHT:
		return AIR_BRAND_NEWCONNAUGHT_LEN;
	case AIR_BRAND_DATONG:
		return AIR_BRAND_DATONG_LEN;
	case AIR_BRAND_DONGYUAN:
		return AIR_BRAND_DONGYUAN_LEN;
	case AIR_BRAND_JIPUSHENG:
		return AIR_BRAND_JIPUSHENG_LEN;
	case AIR_BRAND_DONGYUAN2:
		return AIR_BRAND_DONGYUAN2_LEN;
	case AIR_BRAND_TOYOTOMI:
		return AIR_BRAND_TOYOTOMI_LEN;
	case AIR_BRAND_GOLDSTART:
		return AIR_BRAND_GOLDSTART_LEN;
	case AIR_BRAND_ROSEAREFINE:
		return AIR_BRAND_ROSEAREFINE_LEN;
	case AIR_BRAND_HAMPTON:
		return AIR_BRAND_HAMPTON_LEN;
	case AIR_BRAND_FANTASIA:
		return AIR_BRAND_FANTASIA_LEN;
	case AIR_BRAND_JICAIRUI:
		return AIR_BRAND_JICAIRUI_LEN;
	case AIR_BRAND_JINBEIJING:
		return AIR_BRAND_JINBEIJING_LEN;
	case AIR_BRAND_KANGBAIEN:
		return AIR_BRAND_KANGBAIEN_LEN;
	case AIR_BRAND_CORONA:
		return AIR_BRAND_CORONA_LEN;
	case AIR_BRAND_NEWLATTICE:
		return AIR_BRAND_NEWLATTICE_LEN;
	case AIR_BRAND_KIOWA:
		return AIR_BRAND_KIOWA_LEN;
	case AIR_BRAND_KOMECO:
		return AIR_BRAND_KOMECO_LEN;
	case AIR_BRAND_LANSTART:
		return AIR_BRAND_LANSTART_LEN;
	case AIR_BRAND_CROSS:
		return AIR_BRAND_CROSS_LEN;
	case AIR_BRAND_LELETTER:
		return AIR_BRAND_LELETTER_LEN;
	case AIR_BRAND_HUAMEI:
		return AIR_BRAND_HUAMEI_LEN;
	case AIR_BRAND_MDV:
		return AIR_BRAND_MDV_LEN;
	case AIR_BRAND_BELCANTO:
		return AIR_BRAND_BELCANTO_LEN;
	case AIR_BRAND_MILLER:
		return AIR_BRAND_MILLER_LEN;
	case AIR_BRAND_NATIONAL:
		return AIR_BRAND_NATIONAL_LEN;
	case AIR_BRAND_OAK:
		return AIR_BRAND_OAK_LEN;
	case AIR_BRAND_OUZHENBAO:
		return AIR_BRAND_OUZHENBAO_LEN;
	case AIR_BRAND_PREMIER:
		return AIR_BRAND_PREMIER_LEN;
	case AIR_BRAND_QINGYUAN:
		return AIR_BRAND_QINGYUAN_LEN;
	case AIR_BRAND_THENEW:
		return AIR_BRAND_THENEW_LEN;
	case AIR_BRAND_LINGBAO:
		return AIR_BRAND_LINGBAO_LEN;
	case AIR_BRAND_TWOLING:
		return AIR_BRAND_TWOLING_LEN;
	case AIR_BRAND_LING:
		return AIR_BRAND_LING_LEN;
	case AIR_BRAND_XLING:
		return AIR_BRAND_XLING_LEN;
	case AIR_BRAND_THREEDRILL:
		return AIR_BRAND_THREEDRILL_LEN;
	case AIR_BRAND_SEARS:
		return AIR_BRAND_SEARS_LEN;
	case AIR_BRAND_SAMPO:
		return AIR_BRAND_SAMPO_LEN;
	case AIR_BRAND_SHUANGLU:
		return AIR_BRAND_SHUANGLU_LEN;
	case AIR_BRAND_SOYEA:
		return AIR_BRAND_SOYEA_LEN;
	case AIR_BRAND_EYRE:
		return AIR_BRAND_EYRE_LEN;
	case AIR_BRAND_SONIA:
		return AIR_BRAND_SONIA_LEN;
	case AIR_BRAND_TADIRAN:
		return AIR_BRAND_TADIRAN_LEN;
	case AIR_BRAND_XTIANYUAN:
		return AIR_BRAND_XTIANYUAN_LEN;
	case AIR_BRAND_GENERAL:
		return AIR_BRAND_GENERAL_LEN;
	case AIR_BRAND_UNIAIR:
		return AIR_BRAND_UNIAIR_LEN;
	case AIR_BRAND_MACRO:
		return AIR_BRAND_MACRO_LEN;
	case AIR_BRAND_WEIYOUKANG:
		return AIR_BRAND_WEIYOUKANG_LEN;
	case AIR_BRAND_LGWHISEN:
		return AIR_BRAND_LGWHISEN_LEN;
	case AIR_BRAND_WANSHIYI:
		return AIR_BRAND_WANSHIYI_LEN;
	case AIR_BRAND_LITTLESWAN:
		return AIR_BRAND_LITTLESWAN_LEN;
	case AIR_BRAND_XIERMODEL:
		return AIR_BRAND_XIERMODEL_LEN;
	case AIR_BRAND_SNOW:
		return AIR_BRAND_SNOW_LEN;
	case AIR_BRAND_YAMATSU:
		return AIR_BRAND_YAMATSU_LEN;
	case AIR_BRAND_SUNSHINE:
		return AIR_BRAND_SUNSHINE_LEN;
	case AIR_BRAND_ELECTRA:
		return AIR_BRAND_ELECTRA_LEN;
	case AIR_BRAND_YONGAN:
		return AIR_BRAND_YONGAN_LEN;
	case AIR_BRAND_MOON_RABBIT:
		return AIR_BRAND_MOON_RABBIT_LEN;
	case AIR_BRAND_ZAMIR:
		return AIR_BRAND_ZAMIR_LEN;
	case AIR_BRAND_LONGFU:
		return AIR_BRAND_LONGFU_LEN;
	case AIR_BRAND_DUCKLING:
		return AIR_BRAND_DUCKLING_LEN;
	case AIR_BRAND_WINIA:
		return AIR_BRAND_WINIA_LEN;
	case AIR_BRAND_TRANE:
		return AIR_BRAND_TRANE_LEN;
	case AIR_BRAND_CHINA:
		return AIR_BRAND_CHINA_LEN;
	case AIR_BRAND_KONKA:
		return AIR_BRAND_KONKA_LEN;
	case AIR_BRAND_HELIAN:
		return AIR_BRAND_HELIAN_LEN;
	case AIR_BRAND_SONGLIN:
		return AIR_BRAND_SONGLIN_LEN;
	case AIR_BRAND_DEERFLY:
		return AIR_BRAND_DEERFLY_LEN;
	case AIR_BRAND_FLYCO:
		return AIR_BRAND_FLYCO_LEN;
	case AIR_BRAND_SAKADONGWOODA:
		return AIR_BRAND_SAKADONGWOODA_LEN;
	case AIR_BRAND_KOBE:
		return AIR_BRAND_KOBE_LEN;
	case AIR_BRAND_DATONGCOMPANY:
		return AIR_BRAND_DATONGCOMPANY_LEN;
	case AIR_BRAND_TEAC:
		return AIR_BRAND_TEAC_LEN;
	case AIR_BRAND_TOYO:
		return AIR_BRAND_TOYO_LEN;
	case AIR_BRAND_SONG:
		return AIR_BRAND_SONG_LEN;
	case AIR_BRAND_FORTRESS:
		return AIR_BRAND_FORTRESS_LEN;
	case AIR_BRAND_FUNAI:
		return AIR_BRAND_FUNAI_LEN;
	case AIR_BRAND_GE:
		return AIR_BRAND_GE_LEN;
	case AIR_BRAND_GWELL:
		return AIR_BRAND_GWELL_LEN;
	case AIR_BRAND_TAB:
		return AIR_BRAND_TAB_LEN;
	case AIR_BRAND_HERMAN:
		return AIR_BRAND_HERMAN_LEN;
	case AIR_BRAND_ANCROWN:
		return AIR_BRAND_ANCROWN_LEN;
	case AIR_BRAND_XWANSHIYI:
		return AIR_BRAND_XWANSHIYI_LEN;
	case AIR_BRAND_MODERN:
		return AIR_BRAND_MODERN_LEN;
	case AIR_BRAND_XINLE:
		return AIR_BRAND_XINLE_LEN;
	case AIR_BRAND_WESTINGHOUSE:
		return AIR_BRAND_WESTINGHOUSE_LEN;
	case AIR_BRAND_YUDIAN:
		return AIR_BRAND_YUDIAN_LEN;
	case AIR_BRAND_SWAN:
		return AIR_BRAND_SWAN_LEN;
	case AIR_BRAND_SACON:
		return AIR_BRAND_SACON_LEN;
	case AIR_BRAND_STILLJONAS:
		return AIR_BRAND_STILLJONAS_LEN;
	case AIR_BRAND_RASONIC:
		return AIR_BRAND_RASONIC_LEN;
	case AIR_BRAND_NIKKO:
		return AIR_BRAND_NIKKO_LEN;
	case AIR_BRAND_PROTON:
		return AIR_BRAND_PROTON_LEN;
	case AIR_BRAND_HUAWEI:
		return AIR_BRAND_HUAWEI_LEN;
	case AIR_BRAND_WELLCOME:
		return AIR_BRAND_WELLCOME_LEN;
	case AIR_BRAND_LENNOX:
		return AIR_BRAND_LENNOX_LEN;
	case AIR_BRAND_LIANGFENG:
		return AIR_BRAND_LIANGFENG_LEN;
	case AIR_BRAND_LIKEL:
		return AIR_BRAND_LIKEL_LEN;
	case AIR_BRAND_APTON:
		return AIR_BRAND_APTON_LEN;
	case AIR_BRAND_ALL:
		return AIR_BRAND_ALL_LEN;
	}
}


