/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class elle_homegenius_infrajni_InfraNative */

#ifndef _Included_elle_homegenius_infrajni_InfraNative
#define _Included_elle_homegenius_infrajni_InfraNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     elle_homegenius_infrajni_InfraNative
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_elle_homegenius_infrajni_InfraNative_test
  (JNIEnv *, jobject);

/*
 * Class:     elle_homegenius_infrajni_InfraNative
 * Method:    testInt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_elle_homegenius_infrajni_InfraNative_testInt
  (JNIEnv *, jobject);

/*
 * Class:     elle_homegenius_infrajni_InfraNative
 * Method:    getOneBrandName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_elle_homegenius_infrajni_InfraNative_getOneBrandName
  (JNIEnv *, jobject, jint);

/*
 * Class:     elle_homegenius_infrajni_InfraNative
 * Method:    getBrandLen
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_elle_homegenius_infrajni_InfraNative_getBrandLen
  (JNIEnv *, jobject);

/*
 * Class:     elle_homegenius_infrajni_InfraNative
 * Method:    getAirCommandByBrand
 * Signature: (IIIIIIIII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_elle_homegenius_infrajni_InfraNative_getAirCommandByBrand
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     elle_homegenius_infrajni_InfraNative
 * Method:    getAirCommandById
 * Signature: (IIIIIIII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_elle_homegenius_infrajni_InfraNative_getAirCommandById
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     elle_homegenius_infrajni_InfraNative
 * Method:    getAirOneBrandNameById
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_elle_homegenius_infrajni_InfraNative_getAirOneBrandNameById
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     elle_homegenius_infrajni_InfraNative
 * Method:    getAirBrandLenById
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_elle_homegenius_infrajni_InfraNative_getAirBrandLenById
  (JNIEnv *, jobject, jint);

/*
 * Class:     elle_homegenius_infrajni_InfraNative
 * Method:    getAirAllBrandListLen
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_elle_homegenius_infrajni_InfraNative_getAirAllBrandListLen
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
